on: push

jobs:
  #test:
    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, macos-latest, windows-latest]
    #runs-on: ${{matrix.os}}
    #steps:
    #  - uses: actions/checkout@v2
    #  - uses: goto-bus-stop/setup-zig@v2
    #  - run: zig build test
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build test
      - run: zig fmt --check .
